name: Integration Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB: db_sequelize_mysql
      HOST: localhost
      DB_PASSWORD: password
      DB_USERNAME: root
      DB_DIALECT: mysql
      DB_POOL_MIN: 0
      DB_POOL_MAX: 5
      DB_POOL_ACQUIRE: 30000
      DB_POOL_IDLE: 10000
      APP_PORT: 8080
      USERS_CSV_PATH: /opt/user.csv

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL 8 and MySQL Client
        run: |
          sudo apt-get update -qy
          sudo apt-get install -qy mysql-server-8.0 mysql-client

      - name: Start MySQL Service
        run: sudo service mysql start

      - name: Debug Environment Variables
        run: |
          echo "HOST: $HOST"
          echo "DB_USERNAME: $DB_USERNAME"
          echo "DB_PASSWORD: $DB_PASSWORD"
          echo "DB_NAME: $DB"

      - name: Verify MySQL Root Login
        run: |
          mysql -u root -e "SELECT 1"
        continue-on-error: true

      - name: Create Database
        run: |
          mysql -h localhost -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS db_sequelize_mysql"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
