name: Integration Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB: ${{ secrets.DB }}
      HOST: ${{ secrets.HOST }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      DB_POOL_MIN: ${{ secrets.DB_POOL_MIN }}
      DB_POOL_MAX: ${{ secrets.DB_POOL_MAX }}
      DB_POOL_ACQUIRE: ${{ secrets.DB_POOL_ACQUIRE }}
      DB_POOL_IDLE: ${{ secrets.DB_POOL_IDLE }}
      APP_PORT: ${{ secrets.APP_PORT }}
      USERS_CSV_PATH: ${{ secrets.USERS_CSV_PATH }}

    services:
      mariadb:
        image: getong/mariadb-action:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_USER: ${{secrets.DB_USERNAME}}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{secrets.DB}}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify MariaDB connection
        run: |
          mysql --host $HOST -u$DB_USERNAME -p$DB_PASSWORD -e "SHOW DATABASES"

      - name: Create Database
        run: |
          mysql --host $HOST -u$DB_USERNAME -p$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
