name: Packer format and validate

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Manual triggering

jobs:
  build:
    name: packer format and validate
    runs-on: ubuntu-latest

    env:
      PRODUCT_VERSION: "1.9.4"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Packer Version
        run: packer --version

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init './packer/ami.us-east-1.pkr.hcl'"

      - name: Format Packer Template
        run: "packer fmt -check './packer/ami.us-east-1.pkr.hcl'"

      - name: Validate Packer Template
        run: "packer validate './packer/ami.us-east-1.pkr.hcl'"
