name: Packer format and validate

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Manual triggering

jobs:
  build:
    name: packer format and validate
    runs-on: ubuntu-latest

    env:
      PRODUCT_VERSION: "1.9.4"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Packer Version
        run: packer --version

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init './packer/ami.us-east-1.pkr.hcl'"

      - name: Format Packer Template
        id: fmt
        run: "packer fmt -check=true './packer/ami.us-east-1.pkr.hcl'"

      - name: Echo steps.fmt.outputs
        run: echo "${{ toJson(steps.fmt.outputs) }}"
        
      - name: Check Format Changes
        run: |
          if [[ ${{ steps.fmt.outputs.exitcode }} -ne 0 ]]; then
            echo "Packer format command modified the file. Please run 'packer fmt' to format your code."
            exit 1
          fi
        shell: bash

      - name: Validate Packer Template
        id: validate
        run: "packer validate './packer/ami.us-east-1.pkr.hcl'"

      - name: Check Validation Result
        run: |
          if [[ ${{ steps.validate.outputs.exitcode }} -ne 0 ]]; then
            echo "Packer validation failed. Please fix the issues in your template."
            exit 1
          fi
        shell: bash
