const {DataTypes} = require('sequelize');
const SequelizeFactory = require('../config/orm-config');

const sequelize = SequelizeFactory().get();

const Assignment = sequelize.define("assignment", {
   id: {
      type: DataTypes.UUID, // Set the data type to UUID
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
   },
   name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
   points: {
      type: DataTypes.INTEGER,
      allowNull: false,
      validate: {
         min: 1,
         max: 100,
      },
   },
   num_of_attempts: {
      type: DataTypes.INTEGER,
      allowNull: false,
      validate: {
        min: 1,
        max: 100,
      },
   },
   deadline: {
      type: DataTypes.DATE,
      allowNull: false,
    }
   },
   {
      // Custom field names for the default column names 'createdAt' and 'updatedAt' auto-generated by sequelize
      createdAt: 'assignment_created',
      updatedAt: 'assignment_updated',
    }
);

(async() => {
   try{
      await sequelize.sync()
      console.log("Successfully synced Assignment Table");
   }catch(error){
      console.log("Error syncing assignment table")
   }
})()

module.exports = Assignment;
