const {DataTypes} = require('sequelize');
const SequelizeFactory = require('../config/orm-config');
const logger = require('../utils/logger');
const sequelize = SequelizeFactory().get();

const Submission = sequelize.define("submission", {
   id: {
      type: DataTypes.UUID, // Set the data type to UUID
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
   },
   assignment_id: {
      type: DataTypes.UUID
   },
   submission_url: {
      type: DataTypes.STRING,
      allowNull: false,
    }
   },
   {
      // Custom field names for the default column names 'createdAt' and 'updatedAt' auto-generated by sequelize
      createdAt: 'submission_date',
      updatedAt: 'submission_updated',
    }
);

(async() => {
   try{
      await sequelize.sync()
      console.log("Successfully synced 'submissions' Table");
      logger.info('ORM: Successfully synced "submissions" table');
   }catch(error){
      logger.error('ORM: Error syncing "submissions" table');
      console.log("Error syncing 'submissions' table")
   }
})()

module.exports = Submission;
