const {DataTypes} = require('sequelize');
const SequelizeFactory = require('../config/orm-config');
const {nameValidator} = require('../utils/helpers/non-crud');

const sequelize = SequelizeFactory().get();

const User = sequelize.define("user", {
   id: {
      type: DataTypes.UUID, // Set the data type to UUID
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
   },
   first_name: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
         nameValidator
         },
   },
   last_name: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
         nameValidator
         },
   },
   password: {
      type: DataTypes.STRING,
      allowNull: false,
   },
   email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true, // Ensure usernames are unique
      validate: {
         isEmail: true, // Validate username using email regex
      },
   }
   },
   {
      // Custom field names for the default column names 'createdAt' and 'updatedAt' auto-generated by sequelize
      createdAt: 'account_created',
      updatedAt: 'account_updated',
    }
);

(async() => {
   try{
      await sequelize.sync()
      console.log("Successfully synced User Table");
   }catch(error){
      console.log("Error syncing user table")
   }
})()

module.exports = User;
